// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using first.Data;

#nullable disable

namespace first.Migrations
{
    [DbContext(typeof(CollegeDBContext))]
    partial class CollegeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("first.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Pune",
                            DOB = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jay59@gmail.com",
                            StudentName = "Jaydip"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mumbai",
                            DOB = new DateTime(2001, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mahesh89@gmail.com",
                            StudentName = "Mahesh"
                        },
                        new
                        {
                            Id = 3,
                            Address = "USA",
                            DOB = new DateTime(2004, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sam75@gmail.com",
                            StudentName = "Sam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
